version: "2.2"
services:
  blogs-api:
    build: .
    container_name: blogs-api
    ports:
      - "8081:8081"
    depends_on:
      - redis3306
  redis3306:
    image: redis
    volumes:
      -  /opt/blogs/docker/env/redis/conf:/usr/local/etc/redis
    ports:
      - 3679:6379
      - 3306:3306
    container_name: redis3306
    command: ["redis-server","/usr/local/etc/redis/redis.conf","--appendonly","yes"]
